# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-05 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20181005_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_years',
            field=models.IntegerField(default=0, max_length=10, verbose_name='工作年限'),
        ),
    ]
