# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-04 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180731_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=20, verbose_name='邮箱验证码'),
        ),
    ]
